site_name: Service & Repair Docs
theme: readthedocs
nav:
  - Home: index.md
  - Server:
      - Main: Server/index.md
      - Collections: Server/Collections.md
      - ObjectiveUtil: Server/ObjectiveUtil.md
  - Client:
      - Main: Client/index.md
      - Audio: Client/Audio.md
      - Camera: Client/Camera.md
  - Workflows:
      - Objectives: Workflows/Objectives.md
      - Interface:
          - Handlers: Workflows/UIHandlers.md
          - ObjectiveUtils: Workflows/ObjectiveUtils.md
 - Events:
      - Objective Events: Events/ObjectiveEvents.md

