site_name: Service & Repair Docs
theme: readthedocs
nav:
  - Home: index.md
  - Module Scripts:
      - Collections: ModuleScripts/Collections.md
      - ObjectiveUtil: ModuleScripts/ObjectiveUtil.md
  - Server Scripts:
      - Server: Server.md
  - Events:
      - Objevtive Events: Events/ObjectiveEvents.md
  - Objectives: Objectives.md

