site_name: Service & Repair Docs
theme: readthedocs
nav:
  - Home: index.md
  - Server:
      - Main: Server/index.md
      - Collections: Server/Collections.md
      - Objectives: 
          - ObjectiveUtil: Server/Objectives/ObjectiveUtil.md
          - LaserObjective: 
              - LaserObjective: Server/Objectives/LaserObjective/index.md
              - LaserUtil: Server/Objectives/LaserObjective/LaserUtil.md
              - MirrorSolver: Server/Objectives/LaserObjective/MirrorSolver.md
      - LaserEmitter: Server/LaserEmitter.md
      - Generation:
          - Main: Server/Generation/index.md
          - TileMaskHelper: Server/Generation/TileMaskHelper.md
  - Client:
      - Main: Client/index.md
      - Audio: Client/Audio.md
      - Camera: Client/Camera.md
      - Visuals: Client/Visuals.md
      - Camera: 
          - CameraController: Client/Camera/CameraController.md
      - Interface: 
          - Interface: Client/Interface/index.md
          - ObjectiveHandler: Client/Interface/ObjectiveHandler.md
          - PromptHandler: Client/Interface/PromptHandler.md
  - Workflows:
      - Objectives: Workflows/Objectives.md
      - Creating a Camera: Workflows/CreatingACamera.md
      - Interface:
          - Handlers: Workflows/UIHandlers.md
          - ObjectiveUtils: Workflows/ObjectiveUtils.md
  - Events:
      - Objective Events: Events/ObjectiveEvents.md
  - Lore:
      - The Null: Lore/TheNull.md

