site_name: Service & Repair Docs
theme: readthedocs
nav:
  - Home: index.md
  - Server Scripts:
      - Server: Server.md
  - Events:
      - Objective Events: Events/ObjectiveEvents.md
  - Objectives: Objectives.md
  - Server:
      - Main: Server.md
  - Server Modules:
      - Collections: ServerModules/Collections.md
      - ObjectiveUtil: ServerModules/ObjectiveUtil.md
  - Client:
      - Main: Client.md
  - Client Modules:
      - Audio: ClientModules/Audio.md
      - Camera: ClientModules/Camera.md
      - Visuals: ClientModules/Visuals.md
  - Workflows:
      - Objectives: Objectives.md

